# Feature Engineering. Практическая работа

Сдаётся на проверку.

## Цели практической работы

Научиться: 

*   генерировать новые признаки; 
*   нормализовать и кодировать данные с помощью lambda-функций и библиотеки scikit-learn.

## Что входит в практическую работу

1. Построить признаки из строк.
2. Преобразовать категориальные переменные.
3. Стандартизировать данные.
4. Использовать MinMaxScaler для нормализации данных.
5. Создать признаки на основе дат.
6. Сохранить датафрейм для этапа моделирования.

## Что оценивается
- Программа выдаёт верный ответ на заданном наборе данных.
- Описаны причины выбранного решения, если требуется.
- Код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов.
- При построении графиков название и оси подписаны, выведена легенда, если требуется. 
- Репозиторий проекта содержит осмысленные коммиты, содержащие конкретные реализованные фичи, ветки названы согласно назначению, лишние файлы не хранятся в репозитории.
- В репозитории проекта соблюдена иерархия директорий согласно списку модулей и содержащихся в них тем.
- Репозиторий проекта содержит файлы с данными, полученными в результате выполнения практической работы.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему проверяющему куратору.

## Задача

Мы продолжим исследовать и готовить данные для этапа моделирования.

Вам предстоит работать с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах, представленной в файле `data/vehicles_dataset_upd.csv`. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.

В этой практической работе вы продолжите генерировать дополнительные признаки и завершите подготовку датасета для этапа моделирования.

## Описание датасета:
- `id`— идентификатор записи;
- `url`— URL-записи о продаже;
- `region`— регион;
- `region_url`— URL региона;
- `price`— стоимость;
- `year`— год выпуска;
- `manufacturer`— производитель;
- `model`— модель;
- `condition`— состояние;
- `cylinders`— количество цилиндров;
- `fuel`— тип топлива;
- `odometer`— количество пройденных миль;
- `title_status`— статус;
- `transmission`— коробка передач;
- `VIN`— идентификационный номер;
- `drive`— тип привода;
- `size`— размер;
- `type`— кузов;
- `paint_color`— цвет;
- `image_url`— URL изображения;
- `description`— указанное описание;
- `county`— страна;
- `state`— штат;
- `lat`— широта;
- `long`— долгота;
- `posting_date`— дата размещения объявления о продаже;
- `price_category`— категория цены.

In [1]:
# Импортируйте необходимые библиотеки
import pandas as pd
import matplotlib.pyplot as plt

### Задача 1. Построение признаков из строк

1. Загрузите датасет из `data/vehicles_dataset_upd6.csv`, выведите первые пять записей и список колонок.

In [2]:
# Ваш код здесь
df = pd.read_csv('data/vehicles_dataset_upd6.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,is_jeep,is_honda,is_nissan,x0_diesel,x0_electric,x0_gas,x0_hybrid,x0_other,std_scaled_odometer,std_scaled_price
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,0,0,0,1.0,0.0,0.0,0.0,0.0,-1.079390,2.958509
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0,0,0,0.0,0.0,0.0,0.0,1.0,-0.560115,-0.085826
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,0,0,0,0.0,0.0,1.0,0.0,0.0,-1.292863,1.406256
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.352621,-0.281218
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,0,0,0,0.0,0.0,0.0,0.0,1.0,-0.234311,-0.274017

In [4]:
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'fuel', 'odometer', 'title_status', 'transmission',
       'image_url', 'description', 'state', 'lat', 'long', 'posting_date',
       'price_category', 'date', 'odometer_km', 'odometer/price', 'region_new',
       'region_corrected', 'manufacturer_model', 'desc_len', 'model_in_desc',
       'price_k$', 'age_category', 'model_len', 'model_word_count', 'is_audi',
       'is_ford', 'is_chevrolet', 'is_toyota', 'is_jeep', 'is_honda',
       'is_nissan', 'x0_diesel', 'x0_electric', 'x0_gas', 'x0_hybrid',
       'x0_other', 'std_scaled_odometer', 'std_scaled_price'],
      dtype='object')

2. Выведите список значений и количество уникальных значений для модели автомобиля.

In [14]:
# Ваш код здесь
df.model.unique().tolist()

['2500 crew cab big horn',
 'explorer 4wd 4dr xlt',
 'golf r hatchback',
 'rav4',
 '1 series 128i coupe 2d',
 'fusion se',
 'accord',
 'charger',
 'altima',
 'galant',
 '500 pop',
 'town car',
 'e-series van universal by glaval designer luxury series conversion leather 16" dvd limo lighting bed',
 'g. caravan se',
 'silverado 2500hd 4x4',
 'mustang',
 'maxima sv',
 'civic',
 'explorer',
 'vue v6',
 'tahoe',
 'f-350',
 'f150',
 'clubman',
 'xts sedan 4d',
 '3500',
 '2500 4x4',
 'rogue',
 'silverado 1500',
 'compass 4x4',
 'camry solara 2dr cpe se v6 auto (natl)',
 'silverado',
 'renegade',
 'forte5',
 'f-150',
 'wrangler unlimited all new',
 'mazda3 touring sedan 4d',
 '535i',
 'park avenue',
 'focus',
 'camry',
 'gx',
 'f150 lariat',
 'titan',
 'corolla',
 'colorado extended cab',
 'tiguan 2.0t s',
 'impreza',
 'jetta s',
 'super duty f-250 srw',
 'altima 2.5 s',
 'q5',
 'es 350 f sport sedan 4d',
 'lx450',
 'pilot',
 'Diahatsu',
 'other',
 'sequoia',
 '1500 classic',
 'tucson se awd',
 'sierra 1500',
 'mazda3',
 'grand cherokee laredo sport',
 'nautilus reserve sport',
 'f-150 4wd supercrew 145" platinum',
 'elantra',
 'x1',
 'fusion',
 'camaro',
 'accord sedan sport 1.5t',
 'benz s500',
 'tacoma double cab',
 'tsx sedan 4d',
 'sebring',
 'yukon denali sport utility',
 'cooper s',
 'enclave premium sport',
 'x4',
 'sequioa',
 'xts',
 'xc90',
 'is300 rwd gas sedan auto',
 'f350 super duty',
 'romeo stelvio ti sport',
 'ranger sport extended cab',
 'spark',
 'enclave',
 '7 series 750li xdrive sedan',
 'express 3500 lt',
 'q7',
 'es',
 'wrangler',
 'corolla le',
 'tribute',
 'xv crosstrek',
 'impala',
 'c300 c-300 luxury awd',
 'frontier crew cab',
 'titan xd single cab sv',
 'f-150 xlt 4x4',
 'fit fwd gas hatchback',
 'cc 3.6 vr6 4motion',
 'transit 350',
 'outback 2.5i wagon',
 '1500',
 'q5 premium sport utility 4d',
 'benz',
 'silverado lt crew cab 4x4',
 '2500',
 'passat',
 '350z',
 'focus titanium sedan 4d',
 'optima',
 'camry xse',
 'c10 short box',
 'expedition el',
 'pathfinder',
 'pilot touring sport',
 'challenger',
 '200',
 'taurus',
 'evoque',
 '500 abarth hatchback 2d',
 'x3 xdrive28i sport utility',
 'mazda3 i sv sedan 4d',
 'arcadia 4x4',
 'cr-v',
 'xt6',
 'jetta sportwagen',
 'sante fe',
 'cc',
 '3500 slt',
 'rogue select s sport',
 'c10',
 'versa s',
 'e150 econoline',
 'equinox lt',
 'explorer xlt',
 'yukon xl',
 'sonata se sedan 4d',
 'soul',
 'corolla s',
 'regal turbo',
 'Scion iM Hatchback 4D',
 'lucerne',
 'rav4 hybrid limited sport',
 'super duty f-350 srw',
 'f250 super duty',
 '1500 tradesman quad cab',
 'odyssey',
 's60 t5 premier sedan 4d',
 'yukon slt',
 'transit 250',
 'cruze lt turbo',
 'mkx',
 'sienna',
 '914',
 'transit connect cargo xlt 4',
 'equinox',
 '300c v6',
 'crosstrek',
 'Voltswagon Beetle',
 'sonata se',
 'a6',
 'sierra 1500 double cab slt',
 '550i',
 'sport',
 'town and country',
 'mazda6',
 'challenger srt 392 rwd gas',
 'sorento lx',
 'malibu ls - one owner',
 'wrangler cj5',
 'colorado',
 'THOMAS SCHOOL BUS',
 'c-class',
 'super beetle',
 '500 sport ruby',
 'f-150 xlt',
 'patriot',
 'fj cruiser',
 'trailblazer lt w/1lt',
 'c-max hybrid se wagon 4d',
 '370z nismo coupe 2d',
 'mx-5 miata',
 'malibu',
 'sl-class sl 550',
 'e250 extended',
 'mx-5 miata grand touring',
 'benz e500',
 'f-250',
 'cc4500',
 '328i',
 'm class',
 'nx',
 'escape',
 'Emergency One Fire Truck',
 'sienna xle',
 'corvette grand sport',
 'liberty suv',
 'vibe gt',
 'mustang gt coupe 2d',
 'edge',
 'sonata',
 'model s sedan 4d',
 'chysler 300',
 'express passenger',
 'tacoma',
 's5 premium plus sedan 4d',
 'legacy',
 'transit 150 cargo van',
 '1500 lone star',
 '7 series',
 'accord lx',
 'wrangler unlimited sahara',
 'v6',
 'tucson',
 'dts',
 'frontier crew cab 4x2 sv auto',
 'f350 super duty crew cab',
 '200 limited',
 'navigator',
 'f-150 lariat crew cab 4x4',
 'crv ex awd',
 'rdx',
 'wrangler unlimited rubicon',
 'tiguan limited 2.0t',
 'avalanche 1500',
 's10 pickup',
 'silverado 2500hd',
 'rdx sh-awd a-spec pkg',
 'Genesis G70 2.0T Sedan 4D',
 'suzuki verona',
 'neon',
 'cougar',
 's5 prestige coupe 2d',
 'stinger premium',
 'boxster s',
 'tiguan',
 'suburban 1500',
 'forte koup ex coupe 2d',
 'suburban',
 'grand cherokee',
 'verano',
 'camaro lt coupe 2d',
 'passat 2.0t wolfsburg',
 'prius prime',
 'ridgeline sport pickup 4d',
 'silverado 1500 ld',
 'promaster 2500 cargo van',
 'odyssey touring',
 'sierra 2500 hd',
 '5 series 540i xdrive sedan',
 'sorento 2wdv6 sx',
 'optima lx',
 'xt4 sport suv 4d',
 'wrx sti limited awd',
 'golf gti s hatchback',
 'mkz select sedan 4d',
 'tiguan sel premium',
 'cts-v coupe',
 '1500 sport 4x4 1/2 ton',
 'traverse lt',
 'journey',
 'caprice classic',
 'f250 super duty lariat',
 'rx 350',
 'traverse premier',
 'avenger mainstreet heat',
 '2002 f 450',
 'f150 xlt 4wd f-150 4x4',
 'corvette',
 'limousine',
 'eurovan',
 'mustang cobra svt',
 'rav4 xle',
 'srx',
 'caravan',
 'c70 convertible',
 'cherokee',
 'town & country',
 'mkz hybrid sedan 4d',
 'rivera',
 'tl',
 'crosstrek premium cvt awd',
 '3.2 tl',
 'ranger',
 'sentra',
 'f150 supercrew cab xlt',
 'silverado 1500 lt crew',
 'g37 sedan',
 'charger sxt sedan 4d',
 'model t',
 'k10',
 'mdx',
 'rx8',
 'cayenne 4dr s hybrid',
 'x5 xdrive35i awd',
 '3 series 340i sedan 4d',
 'tundra',
 'silverado 1500 lt',
 '5 series 528i sedan 4d',
 'forte5 lx',
 'highlander',
 'rx 300',
 'sierra',
 '1500 slt',
 '3 series',
 'santa fe',
 'tacoma limited 4x4',
 'pilot ex-l',
 'prius',
 'maxima 3.5 sl',
 'yaris sedan',
 'econoline commercial cutaway',
 'qx50 sport utility 4d',
 'aura',
 'impala lt',
 'outlander sport es',
 'dakota',
 'f250',
 'isuzu pickup',
 'fusion platinum sedan 4d',
 'discovery',
 'eos',
 'pickup 1500',
 'grand cherokee laredo 4wd',
 'gti autobahn',
 'titan xd crew cab sv',
 'sierra 1500 sle/z71 monster',
 'cadenza',
 'genesis coupe 3.8 2d',
 'a5 cabriolet',
 'isuzu npr',
 'patriot sport',
 'outback 3.0 r h6 ll bean',
 'escape sel',
 'Chevey uplander',
 'f-250 sd',
 '6',
 'silverado 1500 ext cab 143.5" wb 4wd ls',
 'qx60 3.5 sport utility',
 'flex se',
 's5 premium plus convertible',
 'sierra all terrrain edition',
 'mariner',
 'durango r/t',
 'sierra 2500hd',
 'macan s sport utility 4d',
 'Genesis G70 3.3T Advanced Sedan',
 'silverado 1500 ls 4x4',
 'f150 xlt supercrew',
 '500 sport 2dr hatchback',
 'cx-9 touring awd',
 'yukon slt 4x4',
 'armada',
 'lacrosse',
 'Hot Rod',
 'Champion Shuttle Bus',
 'lacrosse cx',
 'x5',
 'a4',
 'sierra 2500 hd double cab',
 'f450',
 'gt-r',
 'cvr',
 'santa fe 2.0t sel sport',
 'camaro z28',
 'sierra 1500 crew cab slt',
 'escape se awd',
 'jetta',
 'land cruiser',
 'envision',
 'camry se automatic',
 'Scion tC',
 'g6',
 'model s signature',
 '750xi xdrive m-sport edition',
 'ranger supercrew xlt pickup',
 'silverado 1500 lt ext cab lifted',
 'solara',
 'f700',
 'cooper',
 'corolla le 4dr sedan',
 'cruze',
 'eqinox',
 'g4500',
 'continental sedan 4d',
 'outback',
 'escape xlt 4x4',
 'cx-5 grand touring sport',
 'eclipse',
 'HINO 268A',
 'benz e320',
 'envoy denali',
 'f150 supercrew cab',
 'cougar xr7',
 'regal',
 'e-class',
 'mazda2 sport',
 'tundra crewmax sr5 pickup',
 'q60 3.0t premium coupe',
 'qx60',
 'mazda3 touring hatchback',
 'camry hybrid',
 'venza xle awd',
 'express cargo van',
 'trax',
 'silverado 1500 double',
 'malibu lt',
 'grand cherokee limited',
 'ss sedan 4d',
 'f550',
 'f-pace',
 'terrain',
 'mdx sh-awd sport utility',
 'avalanche z71',
 'quest sv',
 'tacoma access cab trd',
 'dump truck',
 'fiesta',
 'ats luxury sedan 4d',
 'wrangler unlimited sahara, $374.52, $1500 down, 2.9% apr, $374.52, $1500 down, 2.9% apr,',
 'rx7',
 'scion tc',
 'xc90 momentum',
 'sierra 1500 4x4 1/2 ton gas',
 'q5 3.0t premium plus sport',
 '2018',
 'envoy 4x4',
 'elantra gt',
 'e350 passenger van',
 'f350',
 'hyndai elantra',
 'wrangler sport suv 2d',
 'silverado 2500',
 'tacoma prerunner v6',
 'suburban ltz',
 'e-series cargo',
 'avalon hybrid limited',
 'brz limited',
 '1954 Packard Patrician Limousine',
 'ats',
 'accent se sedan 4d',
 'acadia denali',
 'civic ex',
 '4runner',
 'enclave premium group',
 '3',
 'accord cpe ex',
 'all vehicles',
 'charger glhs',
 'tundra sr5 4wd 5.7l 1 owner',
 'c-class c 300',
 'xt5 luxury sport',
 'tacoma trd',
 'tacoma 4x4',
 'f-250 super duty lariat 4x4',
 'a3 tdi premium sedan 4d',
 '4runner sr5 sport utility',
 'f150 platinum',
 'v60 cross country t5',
 '4500',
 'accord ex-l',
 'frontier',
 'tsx 2.4',
 'golf r 4motion',
 'Genesis G80 3.8 Sedan 4D',
 'titan xd',
 '500',
 'wrangler unlimited',
 '500l',
 'outlander gt',
 'xc90 t6 r design awd gas',
 'bronco xlt',
 'Plymouth Barracuda',
 'f-250 super duty',
 'Maserati Quattroporte',
 'model 3',
 'expedition limited',
 'tlx 3.5 sedan 4d',
 'camry le automatic',
 'wrangler sport s utility 2d',
 'silverado 2500 hd',
 'f250 super duty 4x4',
 'versa',
 'trax lt sport utility',
 'camry se',
 'corolla camry',
 'tsx',
 'golf',
 'f-150 4x4 step side',
 'sts',
 'enclave leather sport',
 '300zx 2+2',
 '86 trd special edition',
 'ranger xlt fx4 4x4 1/4 ton',
 '300',
 '4 series 430i xdrive',
 'model a',
 'x3 xdrive30i sport utility',
 'grand caravan sxt',
 'transit connect passenger',
 'cj5',
 'grand caravan',
 'eldorado biarritz',
 'cr-v lx automatic',
 'cj8 scrambler',
 'econoline e350',
 'crosstrek premium',
 'Hummer H2',
 'qx50',
 'hhr ls_panel 4dr wagon',
 'outlander sport',
 'g g37 sport coupe 2d',
 'cx-9',
 'outlander phev sel',
 'panamera',
 'lx 570',
 'sentra sv automatic',
 'benz c300',
 'city express',
 'sonata hybrid',
 'commander',
 'discovery sport se',
 'e46 m3',
 'grand marquis',
 'mercedes-amg',
 'ram1500',
 'f-150 platinum crew ecoboost 3.5l',
 'sable',
 'f150 supercrew cab xl',
 'soul ! wagon 4d',
 'sienna xle awd',
 'traverse',
 'sonoma',
 'mustang gt premium 2dr conv',
 'certified',
 'x5 xdrive30i',
 'sedona',
 'deville',
 'genesis coupe',
 'sonic',
 'civic si sedan 4d',
 'mazda3 i touring hatchback',
 'outback awd 3.6r touring',
 'five hundred sel',
 'dart',
 '1999 International',
 '1500 big horn/lone star',
 'seirra',
 'cooper hardtop',
 'cobalt lt',
 'e-250',
 'f150 xlt 4wd',
 'm3 coupe 2d',
 'avalanche',
 'thunderbird deluxe',
 'super duty f-450 drw',
 'rdx sport utility 4d',
 'model 3 standard range',
 'sorento',
 'transit cargo cargo 250',
 'hardtop cooper s hatchback',
 '5 series 535d xdrive sedan',
 's60 t6 r-design sedan 4d',
 'tacoma double cab pickup',
 'GRAND CARAVAN SXT, 3.6L V6',
 'c 250 sport',
 'f-150 platinum 4x4',
 'pickup',
 'expedition xlt',
 'impala ss',
 'blue bird',
 'veloster n coupe 3d',
 'm-class',
 'e-pace p300 r-dynamic s',
 'a6 45 tfsi premium plus',
 'qx80',
 'encore preferred sport',
 'grand cherokee laredo',
 'gti hatchback sedan',
 'cts 3.6 premium',
 '300 300s sedan 4d',
 'envoy',
 'cts',
 'truck 3500 quad cab',
 's90 t6 momentum sedan 4d',
 'f-250sd',
 'mkx awd',
 '240 dl',
 'focus titanium hatchback 4d',
 'a5 premium plus sedan 4d',
 'silverado 3500',
 'cooper s 2 door cooper s',
 'srx awd',
 'Maserati Ghibli',
 'nv200 sv cargo van',
 'prius c',
 'pt cruiser',
 'focus se',
 'prius v',
 'forester',
 'tsx tech pkg',
 'liberty',
 'windstar limited',
 'sonata sel sedan 4d',
 'terrain sle sport utility 4d',
 'f150 super cab xlt pickup',
 'miata',
 'taurus se',
 'ats 2.0l turbo standard',
 'model s',
 's320',
 'mkx reserve sport',
 '5 series 535i sedan 4d',
 'FORD* FIESTA*',
 'mdx advance pkg sport',
 'focus st hatchback 4d',
 'bel air/150/210',
 'colorado crew cab z71',
 '4 series 430i convertible 2d',
 'silverado 1500 regular',
 'rainier',
 'sienna l minivan 4d',
 'civic sedan',
 'a6 2.0t premium plus sedan',
 'mx-5 miata club',
 'benz ml350 4matic',
 'i-miev',
 'hse 4x4 s',
 'e-pace p250 se sport',
 's-10 ext cab 123" wb ls',
 'tacoma trd off-road full ads coil over adjustable resivoirs kit* koning ultra light 17"wheels*bfg ko2 tires*trd off road*camburg upper control arms*trd pro grill & roof rack*nav*tech pkg*',
 'fj cruiser 4x4',
 '4runner sr5',
 'wrangler sahara',
 'mazda3 touring 2.5',
 'escalade',
 'e-pace p250 s sport',
 'silverado 3500hd',
 'sienna xle 7 passenger',
 'renegade sport suv 4d',
 '5 series',
 'ion',
 'yukon',
 'ranger xlt',
 'accent',
 'durango',
 'elantra se',
 'sedona lx',
 'camaro ss 2ss/rs',
 'avalon xls',
 'deluxe',
 'vibe base',
 'eos komfort',
 '328i gt',
 'international dump truck',
 'ls 460 sedan 4d',
 'aveo',
 'challenger sxt rwd gas',
 '535xi',
 'cooper clubman s',
 'ranger supercab xl pickup',
 'escape se',
 'civic ex sedan',
 'focus st hatchback',
 'es 350 sedan 4d',
 'tundra double cab sr',
 'cooper countryman',
 'civic lx',
 'forte koup',
 'murano sl',
 'pick up',
 'colorado crew cab work',
 'fiesta se',
 'encore gx select sport',
 'x1 xdrive28i',
 'm-class ml 350',
 'enclave essence sport',
 'sierra 2500hd available wifi',
 'sienna se minivan 4d',
 'legacy 2.5i special ed',
 'rl',
 'gto',
 'camry hybrid xle sedan 4d',
 'nv2500 hd cargo',
 'clk-class',
 'ct5 premium luxury',
 'enclave cxl',
 'colorado lt',
 'verano base',
 'tundra 4wd',
 '3-series',
 'sierra 1500 sleextended',
 'impreza 2.5i premium',
 'Isuzu NPR HD GAS REG',
 'b2200',
 'a6 2.0t premium sedan 4d',
 'f-150 truck 4x4',
 'camaro ls',
 '4 series 440i xdrive gran',
 '3i touring',
 'xe 20d sedan 4d',
 'e-class e 300',
 'qx60 luxe sport utility',
 'c 300',
 'caliber',
 '323i',
 'rsx coupe 2.0l automatic leather moon sport wheels',
 '545i',
 'frontier crew cab s',
 's60',
 '5 series 530e iperformance',
 'pacifica touring l fwd',
 'tacoma access cab sr5',
 'jeepster commando',
 '1500 crew cab big horn',
 'tahoe z71 4x4',
 'es 330',
 'svx',
 'caliber sxt',
 'captiva sport ls',
 'tucson sport',
 'expedition eddie bauer',
 'quest sl',
 'forte',
 'f 450 super duty',
 'compass',
 '2500 slt',
 's8',
 '300c hemi',
 'charger gt sedan 4d',
 'pathfinder le',
 '1500 crew cab tradesman',
 'wrangler unlimited sport',
 'ls 430',
 'sprinter cargo vans',
 'acadia',
 'solara se',
 'tundra 4x4',
 'expedition',
 'econoline',
 'plymouth scamp',
 'suburban lt',
 'silverado 1500 work tr',
 'camry le',
 'odyssey exl',
 'xterra',
 'f-250 super duty xlt',
 'international prostar',
 'silverado 1500 crew',
 'f150 super cab lariat',
 'impala ls',
 'scion iq',
 '2500 longhorn mega 4x4',
 'qx80 sport utility 4d',
 'f650',
 'expedition el king ranch',
 'explorer limited automatic',
 'quest',
 'nx 300h sport utility 4d',
 'trailblazer ls 4x4',
 'lifted f150 fx4 4x4 1/2 ton',
 'cobalt',
 'jetta 1.4t s sedan 4d',
 '2500 quad cab',
 'sierra 2500',
 'pathfinder le 4wd',
 'Lotus Diva Roadster',
 'transit connect xlt',
 'encore preferred',
 'mkz sedan 4d',
 'rav4 limited i4 2wd 4-speed automatic',
 'murano',
 'f550 4x4 crew cab',
 'IC IC',
 'silverado 1500 ltz 4x4',
 '1500 crew cab express pickup',
 'santa fe gls',
 'fit',
 'mdx touring w/navi w/res',
 's7 4.0 tfsi prestige',
 'f350 crew cab',
 'Sea Ray Sea Ray',
 'civic si',
 'tundra 1794 edition',
 'SCION XB',
 'atlas',
 'srx~awesome colors~ navigation~ camera~ factory ch',
 'civic lx sedan 4d',
 'atlas sel 4motion',
 'outlander',
 'benz e350',
 'c-7500 multiple uses perfect',
 'encore',
 '6 series',
 'lesabre',
 'sierra 1500 extended cab slt',
 'eclipse cross es',
 'civic hybrid',
 'aveo ls',
 'f150 supercrew cab fx4',
 'es 350',
 'tacoma prerunner',
 'INTERNATIONAL WORKSTAR 7400',
 'traverse ls sport',
 'enclave leather',
 'challenger gt coupe 2d',
 'versa note',
 'International TerraStar',
 'q5 premium plus sport',
 'hse',
 'grand caravan se',
 'camry hybrid le',
 'thunderbird',
 'durango gt sport utility',
 'e350 bucket van',
 '1500 quad cab laramie pickup',
 'quattro tt',
 'kicks',
 'juke nismo',
 'impreza wrx sti',
 'savana',
 's2000',
 'cherokee trailhawk 4x4 gas',
 'fj 62',
 'a6 3.0t prestige sedan 4d',
 'benz sl 320',
 'beetle 1.8t fleet',
 'gladiator',
 'ilx premium',
 'brz limited coupe 2d',
 'willys',
 'scion frs',
 'titan sv',
 'acadia slt',
 'sentra s',
 'hhr',
 'new beetle',
 'escape s',
 'mkz reserve sedan 4d',
 'renegade trailhawk sport',
 'sequoia sr5 platinum',
 'sierra 1500 sle',
 'transit van',
 'wrangler sport',
 'malibu ltz',
 'e350 super duty',
 'g35x',
 'q70',
 'savana 12 passenger',
 'santa fe sport awd',
 'equinox lt awd',
 'eurovan camper',
 '1978 LincolnTown Cars',
 'international 9400i',
 'romeo stelvio',
 'cooper clubman',
 'prius hybrid',
 'c-hr',
 'e-series cargo van',
 'srx4',
 'santa fe gls 4dr suv',
 'mpv',
 'ranger xl 4x2',
 '370z coupe',
 'Flexible Down Payments',
 'cc sport',
 'silverado 2500hd ltz',
 'camry hybrid le sedan 4d',
 'bonanza',
 'enclave avenir sport',
 'mazda3 i sport',
 'gle 400 4matic',
 'sienna xle limited handic',
 'malibu lt sedan 4d',
 'silverado 1500 4x2 re',
 'g37',
 'corvette coupe',
 'sentra sv sedan 4d',
 'c8500',
 'expedition xlt sport',
 'f150 regular cab xl pickup',
 'sierra 1500 regular cab',
 'focus electric hatchback 4d',
 'maxima',
 'a4 quattro',
 'cr-v lx sport utility 4d',
 'cx9',
 'titan pro-4x',
 'is 250 sedan 4d',
 'sl-class',
 'a5 premium sedan 4d',
 'grand caravan passenger se',
 'utility truck',
 'is 250',
 'freestyle awd',
 'expedition max',
 'camaro ls rwd gas',
 '300-series',
 'magnum',
 'blazer 2lt sport',
 'a4 2.0t quattro',
 'tlx',
 '1500 quad cab slt pickup 4d',
 'x5 xdrive35d',
 '325i',
 'hummer h3 4dr 4wd suv',
 'benz c250 coupe',
 'wrangler sport unlimited',
 'f-350 super duty',
 'k10 4x4',
 'g37s',
 'tiguan sel',
 'prius four panel solar',
 '280zx',
 'romeo giulia ti sedan 4d',
 'q50 3.0t luxe sedan 4d',
 'spark lt',
 'cruze lt',
 'excursion',
 'mountaineer',
 'rx',
 'charger scat pack sedan 4d',
 '2007 Silverado crew cab 4x4',
 'Janesville',
 'sierra 1500 double cab',
 'focus ses',
 'cruze 1lt auto',
 'gls new beetle convertible',
 'sierra 1500 elevation',
 'xk8',
 'ranger supercrew xl pickup',
 'ls 400',
 'forte ex hatchback',
 'forester xt premium',
 'navigator sport utility',
 'f-450 super duty',
 'e350',
 'sportage lx sport utility 4d',
 'xj',
 'f150 4x4',
 'transit',
 'liberty limited',
 'FORD/RANGER',
 'freightliner m2',
 'e-pace p300 r-dynamic se',
 'camry xle',
 'rav4 limited',
 'grand caravan se wheelcha',
 'uplander cargo van',
 'promaster cargo van 1500 low roof 118" wb',
 'f250 super duty crew cab',
 'sierra 1500 double cab sle',
 'tacoma access cab pickup',
 '5500',
 'sienna limited awd',
 'legacy 2.5i sedan 4d',
 'pacifica',
 'passport sport suv 4d',
 'patriot high altitude 4x4',
 'durango sxt',
 'navigator l select sport',
 'sienna le',
 'pickup 3500 laramie',
 'legacy 3.0r',
 'rogue sv awd gas suv auto',
 'vandura 3500',
 'silverado high country',
 'gti',
 'f-250 super duty super duty',
 'Isizu NPR',
 'silverado 2500 6.0l 1-owner 4x4 crew*new wheels* clean car-fax!!!',
 'express 1500 cargo van',
 'jetta gli',
 'golf gti',
 'yukon denali',
 'es 300',
 'metris passenger',
 'FordE350',
 'cavalier convertible',
 'rav4 xle sport utility 4d',
 'camaro ss coupe 2d',
 '3 series 330i xdrive sedan',
 'pathfinder se',
 'highlander le sport',
 'International 4300 -',
 'nv passenger',
 'coupe',
 'venza',
 'mkc reserve sport',
 'super duty',
 's5',
 'cooper countryman s all4',
 'tacoma access cab sr',
 'b2300',
 'f350 work truck',
 'pontaic g6',
 'qx60 luxe',
 ...]

In [11]:
df.model.nunique()

3341

3. Количество уникальных значений велико. Попробуем их сократить, оставив только первое слово в наименовании модели. С помощью lambda-функции и преобразования над строками создайте новый признак `short_model`, содержащий только первое слово из наименования модели, выведите его и количество получившихся уникальных значений.

In [17]:
# Ваш код здесь
df['short_model'] = df.apply(lambda x: x.model.split(' ')[0], axis = 1)
df.short_model

0           2500
1       explorer
2           golf
3           rav4
4              1
          ...
9614        rav4
9615    wrangler
9616          a3
9617     cayenne
9618        1500
Name: short_model, Length: 9619, dtype: object

In [19]:
df.short_model.nunique()

943

### Задача 2. Преобразование категориальных переменных

1. Для категориальных переменных `short_model`, `transmission`, `region`, `manufacturer`, `state`, `title_status`, `age_category` распечатайте наименование категории и количество уникальных значений в ней.

In [24]:
# Ваш код здесь
df[['short_model','transmission','region','manufacturer','state','title_status','age_category']].nunique()

short_model     943
transmission      3
region          393
manufacturer     40
state            51
title_status      6
age_category      3
dtype: int64

2. Создайте датафрейм `data`, содержащий только выбранные категориальные переменные.

In [42]:
# Ваш код здесь
data = df[['short_model','transmission','region','manufacturer','state','title_status','age_category']]
data.head()

,short_model,transmission,region,manufacturer,state,title_status,age_category
0,2500,other,chattanooga,ram,tn,clean,new
1,explorer,automatic,north jersey,ford,nj,clean,new
2,golf,other,reno / tahoe,volkswagen,ca,clean,new
3,rav4,automatic,fayetteville,toyota,nc,clean,average
4,1,other,knoxville,bmw,tn,clean,average

3. Создайте объект класса OneHotEncoder, который будет отвечать за преобразование. Уточните, что на выходе должна быть неразреженная матрица.

In [26]:
# Ваш код здесь
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

4. Идентифицируйте параметры преобразования на датафрейме с категориальными переменными.

In [34]:
# Ваш код здесь
ohe.fit(data)

OneHotEncoder(sparse_output=False)

5. Примените преобразование для датафрейма с категориальными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [35]:
# Ваш код здесь
data_trans = ohe.transform(data)
data_trans

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [36]:
data_trans.shape

(9619, 1439)

6. Выведите новые наименования признаков с помощью метода `get_feature_names_out`.

In [40]:
# Ваш код здесь
ohe.get_feature_names_out()

array(['short_model_-benz', 'short_model_1', 'short_model_124', ...,
       'age_category_average', 'age_category_new', 'age_category_old'],
      dtype=object)

7. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [46]:
# Ваш код здесь
df[ohe.get_feature_names_out()]=data_trans
df.head()
#Выдал какую-то ошибку, после добавления новых столбцов. После перезапуска просто выдал результат df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,state_wy,title_status_clean,title_status_lien,title_status_missing,title_status_parts only,title_status_rebuilt,title_status_salvage,age_category_average,age_category_new,age_category_old
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

8. Посмотрите на результат обратного преобразования получившейся матрицы в исходные признаки, используйте `inverse_transform`.

In [48]:
# Ваш код здесь
ohe.inverse_transform(data_trans)

array([['2500', 'other', 'chattanooga', ..., 'tn', 'clean', 'new'],
       ['explorer', 'automatic', 'north jersey', ..., 'nj', 'clean',
        'new'],
       ['golf', 'other', 'reno / tahoe', ..., 'ca', 'clean', 'new'],
       ...,
       ['a3', 'automatic', 'salem', ..., 'or', 'clean', 'average'],
       ['cayenne', 'automatic', 'madison', ..., 'wi', 'clean', 'new'],
       ['1500', 'other', 'norfolk / hampton roads', ..., 'va', 'clean',
        'new']], dtype=object)

### Задача 3. Стандартизация данных

1. Создайте переменную под количественные переменные `lat`, `long`, `year`, `odometer/price`, `desc_len`, `model_in_desc`, `model_len`, `model_word_count` и создайте датафрейм `data`, содержащий только выбранные количественные переменные.

In [50]:
# Ваш код здесь
data = df[['lat','long','year','odometer/price','desc_len','model_in_desc','model_len','model_word_count']]

2. Создайте объект `std_scaler` класса StandardScaler с параметрами по умолчанию, который будет отвечать за стандартизацию.

In [51]:
# Ваш код здесь
from sklearn.preprocessing import StandardScaler
std_scaler=StandardScaler()
std_scaler

StandardScaler()

3. Идентифицируйте параметры преобразования на датафрейме с количественными переменными.

In [52]:
# Ваш код здесь
std_scaler.fit(data)

StandardScaler()

4. Примените преобразование для датафрейма с количественными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [53]:
# Ваш код здесь
data_transform = std_scaler.transform(data)
data_transform

array([[-0.61917248,  0.48424452,  1.32239376, ..., -0.15578836,
         1.16303238,  1.91066901],
       [ 0.38801429,  1.11079989,  0.69597272, ..., -0.15578836,
         0.93208734,  1.23579936],
       [-0.84305905,  0.531185  ,  0.85257798, ..., -0.15578836,
         0.47019727,  0.56092971],
       ...,
       [ 1.10542805, -1.62887477, -0.08705357, ..., -0.15578836,
         1.50944993,  1.91066901],
       [ 0.7739386 ,  0.25195859,  0.53936746, ..., -0.15578836,
        -0.56905538, -0.78880959],
       [-0.33773799,  0.98546471,  0.85257798, ..., -0.15578836,
         1.16303238,  1.91066901]])

5. Создайте наименования новых признаков по шаблону: `lat_std` для `lat` и так далее.

In [54]:
# Ваш код здесь
names = ['lat_std','long_std','year_std','odometer/price_std','desc_len_std','model_in_desc_std','model_len_std','model_word_count_std']

6. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [56]:
# Ваш код здесь
df[names]=data_transform
df.head()
#C:\Users\Георгий\AppData\Local\Temp\ipykernel_29748\237635294.py:2: PerformanceWarning: DataFrame is highly fragmented.  
#This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns 
#at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`df[names]=data_transform
#Эту ошибку он выдавал. Я так понял, его возмуает 'фрагментированность' датафрейма(оно и понятно, при 1493 столбцах) 
#и предлагает использоват pd.concat(axis=1),вместо того способа, что использовал я из урока. 
#При этом, могу ошибаться, вроде с задачей он справился в итоге.

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,age_category_new,age_category_old,lat_std,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,1.0,0.0,-0.619172,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,1.0,0.0,0.388014,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,1.0,0.0,-0.843059,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,0.0,0.0,-0.504509,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,0.0,0.0,-0.460101,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669

### Задача 4. MinMax-нормализация данных

1. Импортируйте MinMaxScaler из `sklearn.preprocessing`.

In [57]:
# Ваш код здесь
from sklearn.preprocessing import MinMaxScaler

2. Создайте датафрейм, содержащий переменные `lat` и `long`.

In [58]:
# Ваш код здесь
data1 = df[['lat','long']]
data1.head()

         lat       long
0  35.060000 -85.250000
1  40.821805 -74.061962
2  33.779214 -84.411811
3  35.715954 -78.655304
4  35.970000 -83.940000

3. Повторите действия пунктов 2–6 из задачи 3 для добавления в исходный датафрейм признаков `lat_mm` и `long_mm`. Выведите получившийся датафрейм.

In [59]:
# Ваш код здесь
min_max_scaler=MinMaxScaler()
min_max_scaler

MinMaxScaler()

In [60]:
min_max_scaler.fit(data1)

MinMaxScaler()

In [62]:
data1_trans = min_max_scaler.transform(data1)

In [64]:
names1 = ['lat_mm','long_mm']
df[names1]=data1_trans
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,lat_std,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std,lat_mm,long_mm
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,-0.619172,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669,0.341769,0.288699
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0.388014,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799,0.468665,0.333055
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,-0.843059,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930,0.313561,0.292022
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,-0.504509,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810,0.356215,0.314844
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,-0.460101,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669,0.361810,0.293893

4. Создайте переменную под географические признаки `lat`, `lat_std`, `lat_mm`, `long`, `long_std`, `long_mm` и выведите их. Посмотрите на различия в значениях для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [65]:
# Ваш код здесь
geographical_features = df[['lat','lat_std','lat_mm','long','long_std','long_mm']]
geographical_features

            lat   lat_std    lat_mm        long  long_std   long_mm
0     35.060000 -0.619172  0.341769  -85.250000  0.484245  0.288699
1     40.821805  0.388014  0.468665  -74.061962  1.110800  0.333055
2     33.779214 -0.843059  0.313561  -84.411811  0.531185  0.292022
3     35.715954 -0.504509  0.356215  -78.655304  0.853562  0.314844
4     35.970000 -0.460101  0.361810  -83.940000  0.557607  0.293893
...         ...       ...       ...         ...       ...       ...
9614  42.123900  0.615626  0.497341  -79.189500  0.823646  0.312727
9615  43.216990  0.806702  0.521415  -77.755610  0.903947  0.318411
9616  44.925908  1.105428  0.559052 -122.982753 -1.628875  0.139104
9617  43.029559  0.773939  0.517287  -89.397796  0.251959  0.272255
9618  36.670000 -0.337738  0.377227  -76.300000  0.985465  0.324182

[9619 rows x 6 columns]

5. Выведите описательные статистики для всех географических признаков. Посмотрите на различия в статистиках для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [68]:
# Ваш код здесь
geographical_features.describe()

,lat,lat_std,lat_mm,long,long_std,long_mm
count,9619.000000,9.619000e+03,9619.000000,9619.000000,9.619000e+03,9619.000000
mean,38.602095,2.105257e-16,0.419779,-93.896875,-4.498602e-16,0.254418
std,5.720989,1.000052e+00,0.125997,17.857352,1.000052e+00,0.070797
min,19.541726,-3.331829e+00,0.000000,-158.069300,-3.593801e+00,0.000000
25%,34.920000,-6.436450e-01,0.338685,-106.944340,-7.306875e-01,0.202690
50%,39.300000,1.219966e-01,0.435149,-87.845800,3.388739e-01,0.278408
75%,42.382100,6.607601e-01,0.503028,-80.678711,7.402470e-01,0.306822
max,64.947500,4.605283e+00,1.000000,94.163200,1.053179e+01,1.000000

6. Выведите матрицу корреляций для всех географических признаков, чтобы убедиться, что нормализация признаков сохранила свойства исходных признаков.

In [80]:
# Ваш код здесь
print(f'Стандартизация признака long {df.long.corr(df.long_std)}')
print(f'MinMax-преобразование признака long {df.long.corr(df.long_mm)}')
print(f'Стандартизация признака lat {df.lat.corr(df.lat_std)}')
print(f'MinMax-преобразование признака lat {df.lat.corr(df.lat_mm)}')
#Не совсем понял, что имеется ввиду под "матрицей корреляции". Вывел значения коэффициента корреляции Пирсона.

Стандартизация признака long 0.9999999999999991
MinMax-преобразование признака long 0.999999999999999
Стандартизация признака lat 1.0
MinMax-преобразование признака lat 1.0

### Задача 5. Признаки на основе дат

1. Выведите по отдельности колонки `posting_date` и `date`.

In [81]:
# Ваш код здесь
df['posting_date']

0       2021-04-17T12:30:50-0400
1       2021-05-03T15:40:21-0400
2       2021-04-28T03:52:20-0700
3       2021-04-17T10:08:57-0400
4       2021-04-08T15:10:56-0400
                  ...
9614    2021-04-10T16:33:57-0400
9615    2021-05-03T09:36:30-0400
9616    2021-04-22T12:14:01-0700
9617    2021-04-14T09:14:42-0500
9618    2021-04-24T13:50:49-0400
Name: posting_date, Length: 9619, dtype: object

In [82]:
df.date

0       2021-04-17 16:30:50+00:00
1       2021-05-03 19:40:21+00:00
2       2021-04-28 10:52:20+00:00
3       2021-04-17 14:08:57+00:00
4       2021-04-08 19:10:56+00:00
                  ...
9614    2021-04-10 20:33:57+00:00
9615    2021-05-03 13:36:30+00:00
9616    2021-04-22 19:14:01+00:00
9617    2021-04-14 14:14:42+00:00
9618    2021-04-24 17:50:49+00:00
Name: date, Length: 9619, dtype: object

2. Ранее преобразованная колонка `date` после сохранения в файл и загрузки из него содержит данные в строковом формате, поэтому измените её тип c помощью `pd.to_datetime`.

In [83]:
# Ваш код здесь
df.date = pd.to_datetime(df.date)

3. Несколькими способами извлеките номер месяца продажи автомобиля.

3.1. Из переменной `posting_date` с помощью lambda-функции и операций над строками.

In [87]:
# Ваш код здесь
df.apply(lambda x: x.posting_date.split('-')[1], axis = 1)

0       04
1       05
2       04
3       04
4       04
        ..
9614    04
9615    05
9616    04
9617    04
9618    04
Length: 9619, dtype: object

3.2. Из переменной `date` с помощью lambda-функции и метода `month`.

In [89]:
# Ваш код здесь
df.apply(lambda x: x.date.month, axis = 1)

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Length: 9619, dtype: int64

3.3. Из переменной `date` с помощью `dt` и метода `month`.

In [93]:
# Ваш код здесь
df.date.dt.month
#Вроде, раньше не пользовались таким методом dt.

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Name: date, Length: 9619, dtype: int32

4. Создайте любым из способов (3.2 или 3.3) признак `month`, обозначающий номер месяца размещения объявления о продаже автомобиля, и распечатайте его.

In [98]:
# Ваш код здесь
print(f'Номер месяца размещения объвления о продаже автомобиля:\n{df.date.dt.month.tolist()}')

Номер месяца размещения объвления о продаже автомобиля:

In [148]:
df['month']=df.date.dt.month
df.month

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Name: month, Length: 9619, dtype: int32

5. Создайте признак `dayofweek`, обозначающий день недели размещения объявления о продаже автомобиля, и распечатайте его.

In [145]:
# Ваш код здесь
dayofweek_num = df.date.dt.dayofweek
dayofweek_dict = {0:'monday',1:'tuesday',2:'wednesday',3:'thursday',4:'friday',5:'saturday',6:'sunday'}
dayofweek = []
for x in range(len(dayofweek_num)):
    if dayofweek_num[x] in dayofweek_dict:
        n=dayofweek_num[x]
        dayofweek.append(dayofweek_dict[n])
dayofweek

['saturday',
 'monday',
 'wednesday',
 'saturday',
 'thursday',
 'tuesday',
 'friday',
 'friday',
 'wednesday',
 'friday',
 'tuesday',
 'wednesday',
 'wednesday',
 'thursday',
 'tuesday',
 'thursday',
 'monday',
 'friday',
 'thursday',
 'saturday',
 'sunday',
 'wednesday',
 'monday',
 'thursday',
 'sunday',
 'friday',
 'friday',
 'thursday',
 'thursday',
 'thursday',
 'tuesday',
 'thursday',
 'tuesday',
 'thursday',
 'thursday',
 'sunday',
 'friday',
 'monday',
 'friday',
 'monday',
 'wednesday',
 'friday',
 'wednesday',
 'tuesday',
 'thursday',
 'wednesday',
 'saturday',
 'monday',
 'monday',
 'monday',
 'saturday',
 'friday',
 'tuesday',
 'friday',
 'monday',
 'thursday',
 'friday',
 'monday',
 'saturday',
 'sunday',
 'wednesday',
 'tuesday',
 'tuesday',
 'tuesday',
 'sunday',
 'sunday',
 'friday',
 'sunday',
 'wednesday',
 'wednesday',
 'tuesday',
 'tuesday',
 'wednesday',
 'tuesday',
 'thursday',
 'saturday',
 'friday',
 'thursday',
 'tuesday',
 'tuesday',
 'friday',
 'monday',
 'wednesday',
 'sunday',
 'tuesday',
 'tuesday',
 'friday',
 'monday',
 'saturday',
 'thursday',
 'saturday',
 'wednesday',
 'thursday',
 'tuesday',
 'saturday',
 'tuesday',
 'sunday',
 'wednesday',
 'friday',
 'tuesday',
 'saturday',
 'thursday',
 'friday',
 'tuesday',
 'friday',
 'saturday',
 'sunday',
 'friday',
 'monday',
 'thursday',
 'saturday',
 'sunday',
 'wednesday',
 'thursday',
 'tuesday',
 'thursday',
 'saturday',
 'sunday',
 'friday',
 'wednesday',
 'monday',
 'tuesday',
 'tuesday',
 'monday',
 'monday',
 'tuesday',
 'saturday',
 'saturday',
 'saturday',
 'thursday',
 'monday',
 'friday',
 'saturday',
 'thursday',
 'friday',
 'tuesday',
 'monday',
 'tuesday',
 'saturday',
 'saturday',
 'sunday',
 'friday',
 'tuesday',
 'thursday',
 'thursday',
 'sunday',
 'thursday',
 'friday',
 'sunday',
 'saturday',
 'thursday',
 'thursday',
 'friday',
 'monday',
 'monday',
 'saturday',
 'tuesday',
 'sunday',
 'tuesday',
 'tuesday',
 'sunday',
 'friday',
 'monday',
 'friday',
 'sunday',
 'monday',
 'wednesday',
 'tuesday',
 'saturday',
 'sunday',
 'saturday',
 'thursday',
 'saturday',
 'saturday',
 'sunday',
 'friday',
 'wednesday',
 'friday',
 'tuesday',
 'tuesday',
 'thursday',
 'saturday',
 'thursday',
 'friday',
 'friday',
 'saturday',
 'tuesday',
 'tuesday',
 'friday',
 'wednesday',
 'saturday',
 'saturday',
 'monday',
 'saturday',
 'saturday',
 'saturday',
 'wednesday',
 'tuesday',
 'monday',
 'friday',
 'wednesday',
 'friday',
 'thursday',
 'friday',
 'saturday',
 'saturday',
 'wednesday',
 'friday',
 'wednesday',
 'tuesday',
 'sunday',
 'sunday',
 'saturday',
 'wednesday',
 'friday',
 'sunday',
 'saturday',
 'tuesday',
 'friday',
 'saturday',
 'saturday',
 'friday',
 'friday',
 'friday',
 'tuesday',
 'monday',
 'friday',
 'monday',
 'sunday',
 'sunday',
 'thursday',
 'wednesday',
 'tuesday',
 'monday',
 'sunday',
 'monday',
 'saturday',
 'thursday',
 'friday',
 'thursday',
 'tuesday',
 'monday',
 'monday',
 'sunday',
 'sunday',
 'sunday',
 'tuesday',
 'friday',
 'tuesday',
 'tuesday',
 'monday',
 'monday',
 'wednesday',
 'saturday',
 'saturday',
 'saturday',
 'monday',
 'saturday',
 'sunday',
 'saturday',
 'monday',
 'sunday',
 'saturday',
 'saturday',
 'saturday',
 'saturday',
 'friday',
 'thursday',
 'friday',
 'saturday',
 'thursday',
 'friday',
 'saturday',
 'thursday',
 'sunday',
 'wednesday',
 'tuesday',
 'saturday',
 'monday',
 'tuesday',
 'sunday',
 'monday',
 'wednesday',
 'friday',
 'friday',
 'tuesday',
 'friday',
 'tuesday',
 'friday',
 'tuesday',
 'tuesday',
 'friday',
 'tuesday',
 'wednesday',
 'sunday',
 'sunday',
 'tuesday',
 'monday',
 'wednesday',
 'friday',
 'tuesday',
 'tuesday',
 'friday',
 'sunday',
 'monday',
 'tuesday',
 'thursday',
 'tuesday',
 'saturday',
 'friday',
 'friday',
 'friday',
 'saturday',
 'monday',
 'wednesday',
 'wednesday',
 'tuesday',
 'saturday',
 'friday',
 'monday',
 'thursday',
 'saturday',
 'tuesday',
 'saturday',
 'wednesday',
 'tuesday',
 'friday',
 'tuesday',
 'monday',
 'sunday',
 'wednesday',
 'thursday',
 'monday',
 'saturday',
 'saturday',
 'saturday',
 'tuesday',
 'thursday',
 'saturday',
 'saturday',
 'wednesday',
 'friday',
 'tuesday',
 'wednesday',
 'sunday',
 'monday',
 'tuesday',
 'tuesday',
 'sunday',
 'friday',
 'tuesday',
 'friday',
 'wednesday',
 'tuesday',
 'sunday',
 'thursday',
 'sunday',
 'sunday',
 'friday',
 'monday',
 'thursday',
 'tuesday',
 'friday',
 'friday',
 'tuesday',
 'wednesday',
 'saturday',
 'tuesday',
 'saturday',
 'sunday',
 'friday',
 'friday',
 'friday',
 'sunday',
 'wednesday',
 'saturday',
 'sunday',
 'friday',
 'monday',
 'saturday',
 'thursday',
 'wednesday',
 'tuesday',
 'sunday',
 'sunday',
 'saturday',
 'friday',
 'sunday',
 'monday',
 'friday',
 'thursday',
 'sunday',
 'friday',
 'monday',
 'saturday',
 'friday',
 'tuesday',
 'tuesday',
 'thursday',
 'friday',
 'saturday',
 'monday',
 'saturday',
 'friday',
 'sunday',
 'thursday',
 'thursday',
 'saturday',
 'sunday',
 'wednesday',
 'friday',
 'saturday',
 'monday',
 'wednesday',
 'monday',
 'sunday',
 'saturday',
 'monday',
 'friday',
 'saturday',
 'monday',
 'tuesday',
 'tuesday',
 'friday',
 'saturday',
 'saturday',
 'thursday',
 'wednesday',
 'tuesday',
 'sunday',
 'saturday',
 'thursday',
 'monday',
 'wednesday',
 'wednesday',
 'sunday',
 'tuesday',
 'tuesday',
 'tuesday',
 'monday',
 'monday',
 'friday',
 'tuesday',
 'saturday',
 'monday',
 'monday',
 'wednesday',
 'sunday',
 'tuesday',
 'thursday',
 'tuesday',
 'monday',
 'thursday',
 'monday',
 'wednesday',
 'tuesday',
 'tuesday',
 'tuesday',
 'tuesday',
 'monday',
 'tuesday',
 'friday',
 'thursday',
 'sunday',
 'saturday',
 'monday',
 'wednesday',
 'sunday',
 'monday',
 'monday',
 'saturday',
 'tuesday',
 'saturday',
 'tuesday',
 'sunday',
 'saturday',
 'tuesday',
 'saturday',
 'wednesday',
 'saturday',
 'friday',
 'wednesday',
 'tuesday',
 'monday',
 'thursday',
 'friday',
 'monday',
 'wednesday',
 'tuesday',
 'friday',
 'sunday',
 'monday',
 'saturday',
 'monday',
 'wednesday',
 'saturday',
 'saturday',
 'monday',
 'saturday',
 'saturday',
 'thursday',
 'tuesday',
 'monday',
 'sunday',
 'thursday',
 'saturday',
 'sunday',
 'tuesday',
 'saturday',
 'saturday',
 'friday',
 'tuesday',
 'tuesday',
 'thursday',
 'tuesday',
 'tuesday',
 'sunday',
 'saturday',
 'thursday',
 'monday',
 'friday',
 'monday',
 'monday',
 'friday',
 'friday',
 'monday',
 'sunday',
 'wednesday',
 'monday',
 'friday',
 'wednesday',
 'sunday',
 'monday',
 'monday',
 'monday',
 'saturday',
 'tuesday',
 'sunday',
 'tuesday',
 'thursday',
 'friday',
 'friday',
 'saturday',
 'saturday',
 'wednesday',
 'saturday',
 'thursday',
 'friday',
 'tuesday',
 'thursday',
 'tuesday',
 'wednesday',
 'saturday',
 'thursday',
 'saturday',
 'tuesday',
 'thursday',
 'tuesday',
 'wednesday',
 'thursday',
 'wednesday',
 'friday',
 'saturday',
 'wednesday',
 'wednesday',
 'monday',
 'friday',
 'sunday',
 'tuesday',
 'friday',
 'saturday',
 'friday',
 'friday',
 'tuesday',
 'monday',
 'saturday',
 'tuesday',
 'tuesday',
 'sunday',
 'sunday',
 'friday',
 'tuesday',
 'monday',
 'sunday',
 'monday',
 'tuesday',
 'monday',
 'saturday',
 'friday',
 'tuesday',
 'tuesday',
 'monday',
 'thursday',
 'saturday',
 'friday',
 'saturday',
 'wednesday',
 'friday',
 'tuesday',
 'friday',
 'thursday',
 'monday',
 'friday',
 'friday',
 'friday',
 'sunday',
 'friday',
 'saturday',
 'monday',
 'wednesday',
 'saturday',
 'wednesday',
 'tuesday',
 'monday',
 'tuesday',
 'thursday',
 'wednesday',
 'thursday',
 'wednesday',
 'friday',
 'saturday',
 'tuesday',
 'monday',
 'wednesday',
 'thursday',
 'saturday',
 'thursday',
 'wednesday',
 'monday',
 'monday',
 'thursday',
 'monday',
 'friday',
 'friday',
 'monday',
 'saturday',
 'thursday',
 'friday',
 'friday',
 'friday',
 'tuesday',
 'tuesday',
 'sunday',
 'wednesday',
 'sunday',
 'sunday',
 'tuesday',
 'monday',
 'monday',
 'friday',
 'wednesday',
 'saturday',
 'sunday',
 'wednesday',
 'friday',
 'tuesday',
 'friday',
 'sunday',
 'friday',
 'sunday',
 'thursday',
 'tuesday',
 'saturday',
 'monday',
 'monday',
 'wednesday',
 'sunday',
 'thursday',
 'saturday',
 'tuesday',
 'tuesday',
 'tuesday',
 'sunday',
 'sunday',
 'friday',
 'monday',
 'tuesday',
 'tuesday',
 'friday',
 'tuesday',
 'tuesday',
 'wednesday',
 'saturday',
 'saturday',
 'thursday',
 'saturday',
 'sunday',
 'sunday',
 'tuesday',
 'tuesday',
 'monday',
 'saturday',
 'friday',
 'wednesday',
 'wednesday',
 'thursday',
 'monday',
 'saturday',
 'saturday',
 'tuesday',
 'sunday',
 'saturday',
 'tuesday',
 'tuesday',
 'friday',
 'saturday',
 'monday',
 'thursday',
 'friday',
 'friday',
 'tuesday',
 'monday',
 'monday',
 'friday',
 'monday',
 'wednesday',
 'friday',
 'thursday',
 'monday',
 'tuesday',
 'tuesday',
 'monday',
 'wednesday',
 'friday',
 'monday',
 'saturday',
 'thursday',
 'sunday',
 'saturday',
 'friday',
 'thursday',
 'friday',
 'friday',
 'thursday',
 'wednesday',
 'monday',
 'thursday',
 'wednesday',
 'friday',
 'friday',
 'monday',
 'thursday',
 'monday',
 'monday',
 'tuesday',
 'saturday',
 'friday',
 'monday',
 'monday',
 'friday',
 'monday',
 'wednesday',
 'tuesday',
 'wednesday',
 'thursday',
 'tuesday',
 'friday',
 'monday',
 'friday',
 'wednesday',
 'tuesday',
 'tuesday',
 'sunday',
 'tuesday',
 'tuesday',
 'monday',
 'tuesday',
 'wednesday',
 'tuesday',
 'thursday',
 'monday',
 'friday',
 'thursday',
 'saturday',
 'friday',
 'friday',
 'sunday',
 'tuesday',
 'thursday',
 'monday',
 'monday',
 'tuesday',
 'sunday',
 'thursday',
 'friday',
 'saturday',
 'friday',
 'saturday',
 'sunday',
 'sunday',
 'tuesday',
 'saturday',
 'saturday',
 'monday',
 'saturday',
 'friday',
 'saturday',
 'monday',
 'friday',
 'sunday',
 'thursday',
 'saturday',
 'friday',
 'thursday',
 'friday',
 'friday',
 'friday',
 'monday',
 'thursday',
 'monday',
 'thursday',
 'sunday',
 'thursday',
 'wednesday',
 'tuesday',
 'thursday',
 'friday',
 'friday',
 'tuesday',
 'thursday',
 'monday',
 'friday',
 'thursday',
 'tuesday',
 'sunday',
 'saturday',
 'sunday',
 'friday',
 'wednesday',
 'wednesday',
 'sunday',
 'tuesday',
 'monday',
 'friday',
 'thursday',
 'monday',
 'saturday',
 'saturday',
 'thursday',
 'thursday',
 'tuesday',
 'monday',
 'monday',
 'tuesday',
 'saturday',
 'tuesday',
 'tuesday',
 'saturday',
 'friday',
 'tuesday',
 'tuesday',
 'tuesday',
 'friday',
 'thursday',
 'monday',
 'friday',
 'sunday',
 'thursday',
 'tuesday',
 'thursday',
 'thursday',
 'tuesday',
 'monday',
 'tuesday',
 'wednesday',
 'wednesday',
 'thursday',
 'saturday',
 'sunday',
 'tuesday',
 'thursday',
 'monday',
 'friday',
 'wednesday',
 'saturday',
 'tuesday',
 'friday',
 'monday',
 'friday',
 'tuesday',
 'monday',
 'monday',
 'friday',
 'tuesday',
 'saturday',
 'thursday',
 'saturday',
 'saturday',
 'wednesday',
 'tuesday',
 'saturday',
 'thursday',
 'monday',
 'monday',
 'sunday',
 'tuesday',
 'wednesday',
 'sunday',
 'saturday',
 'monday',
 'sunday',
 'thursday',
 'wednesday',
 'tuesday',
 'wednesday',
 'thursday',
 'friday',
 'wednesday',
 'sunday',
 'monday',
 'friday',
 'friday',
 'sunday',
 'wednesday',
 'saturday',
 'tuesday',
 'tuesday',
 'saturday',
 'monday',
 'monday',
 'wednesday',
 'tuesday',
 'friday',
 'sunday',
 'saturday',
 'tuesday',
 'wednesday',
 'monday',
 'friday',
 'sunday',
 'friday',
 'sunday',
 'saturday',
 'wednesday',
 'wednesday',
 'tuesday',
 'sunday',
 'saturday',
 'wednesday',
 'tuesday',
 'friday',
 'saturday',
 'monday',
 'monday',
 'thursday',
 'monday',
 'sunday',
 'thursday',
 'saturday',
 'friday',
 'wednesday',
 'thursday',
 'friday',
 'sunday',
 'sunday',
 'friday',
 'monday',
 'sunday',
 'monday',
 'thursday',
 'thursday',
 'monday',
 'thursday',
 'thursday',
 'tuesday',
 'thursday',
 'wednesday',
 'saturday',
 'friday',
 'wednesday',
 'friday',
 'tuesday',
 'monday',
 'saturday',
 'wednesday',
 'saturday',
 'wednesday',
 'thursday',
 'wednesday',
 'thursday',
 'thursday',
 'monday',
 'wednesday',
 'sunday',
 'saturday',
 'sunday',
 'thursday',
 'monday',
 'tuesday',
 'saturday',
 'monday',
 'wednesday',
 'monday',
 'friday',
 'friday',
 'tuesday',
 'saturday',
 'tuesday',
 'thursday',
 'tuesday',
 ...]

In [150]:
df['dayofweek']=df.date.dt.dayofweek
df.dayofweek

0       5
1       0
2       2
3       5
4       3
       ..
9614    5
9615    0
9616    3
9617    2
9618    5
Name: dayofweek, Length: 9619, dtype: int32

6. Создайте признак `diff_years`, обозначающий количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля, и распечатайте его. Дополнительные корректировки не применяйте.

In [160]:
# Ваш код здесь
df['diff_years']=df.apply(lambda x: x.date.year-x.year, axis = 1)
df.diff_years

0        1
1        5
2        4
3        8
4        9
        ..
9614    19
9615    13
9616    10
9617     6
9618     4
Name: diff_years, Length: 9619, dtype: int64

7. Примените стандартизацию к новым признаками и сохраните результат в новые признаки вида `month_std`.

In [167]:
# Ваш код здесь
new_names = ['month_std','dayofweek_std','diff_years_std']
std_scaler.fit(df[['month','dayofweek','diff_years']])
scaled_features = std_scaler.transform(df[['month','dayofweek','diff_years']])
df[new_names]=scaled_features
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,model_len_std,model_word_count_std,lat_mm,long_mm,month,dayofweek,diff_years,month_std,dayofweek_std,diff_years_std
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,1.163032,1.910669,0.341769,0.288699,4,5,1,-0.615846,1.120284,-1.322394
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0.932087,1.235799,0.468665,0.333055,5,0,5,1.623784,-1.374972,-0.695973
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,0.470197,0.560930,0.313561,0.292022,4,2,4,-0.615846,-0.376870,-0.852578
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,-0.915473,-0.788810,0.356215,0.314844,4,5,8,-0.615846,1.120284,-0.226157
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,1.163032,1.910669,0.361810,0.293893,4,3,9,-0.615846,0.122182,-0.069552

### Задача 6. Сохранение датафрейма для этапа моделирования

1. Удалите колонки, которые были исходными для формирования признаков, а также новые признаки, которые были добавлены с целью обучения.  Сохраните новый датафрейм в переменную `df_prepared`.

In [185]:
# Допишите код

columns_for_drop = ['year', 'url', 'region', 'region_url', 'manufacturer',
                    'model', 'fuel', 'odometer', 'title_status', 'transmission',
                    'image_url', 'description', 'state', 'lat', 'long', 'posting_date',
                    'odometer_km', 'odometer/price', 'region_new', 'region_corrected', 'manufacturer_model',
                    'desc_len', 'model_in_desc', 'price_k$', 'age_category', 'model_len', 'model_word_count',
                    'short_model', 'lat_mm', 'long_mm', 'date', 'std_scaled_price',
                    'month', 'dayofweek', 'diff_years',
                    'odometer/price_std']
df_prepared = df.drop(columns=columns_for_drop)
df_prepared.head()

,id,price,price_category,is_audi,is_ford,is_chevrolet,is_toyota,is_jeep,is_honda,is_nissan,...,lat_std,long_std,year_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std,month_std,dayofweek_std,diff_years_std
0,7308295377,54990,high,0,0,0,0,0,0,0,...,-0.619172,0.484245,1.322394,0.632075,-0.155788,1.163032,1.910669,-0.615846,1.120284,-1.322394
1,7316380095,16942,medium,0,1,0,0,0,0,0,...,0.388014,1.110800,0.695973,-0.646781,-0.155788,0.932087,1.235799,1.623784,-1.374972,-0.695973
2,7313733749,35590,high,0,0,0,0,0,0,0,...,-0.843059,0.531185,0.852578,0.560744,-0.155788,0.470197,0.560930,-0.615846,-0.376870,-0.852578
3,7308210929,14500,medium,0,0,0,1,0,0,0,...,-0.504509,0.853562,0.226157,0.180435,-0.155788,-0.915473,-0.788810,-0.615846,1.120284,-0.226157
4,7303797340,14590,medium,0,0,0,0,0,0,0,...,-0.460101,0.557607,0.069552,0.766366,-0.155788,1.163032,1.910669,-0.615846,0.122182,-0.069552

2. Распечатайте оставшийся список колонок и размерность финального датафрейма.

In [191]:
# Ваш код здесь
print(f'Список колонок: \n {df_prepared.columns.tolist()}\n')
print(f'Размерность финального датафрейма: \n {df_prepared.shape}')

Список колонок:

3. Запишите преобразованный датафрейм в файл `data/vehicles_dataset_prepared.csv`, индекс не сохраняйте.

In [192]:
# Ваш код здесь
df_prepared.to_csv('data/vehicles_dataset_prepared.csv', index=False)

## Описание преобразованного датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`– категория цены.